export const ClassNames = ["AAS", "ACC", "AERO", "AEROSP", "AES", "ALA", "AMCULT", "ANATOMY", "ANTHRARC", "ANTHRBIO", "ANTHRCUL", "APPPHYS", "ARABAM", 
            "ARABIC", "ARCH", "ARMENIAN", "ARTDES", "ARTSADMN", "ASIAN", "ASIANLAN", "ASIANPAM", "ASTRO", "AUTO", "BA", "BCOM", "BCS", "BE",
            "BIOINF", "BIOLCHEM", "BIOLOGY", "BIOMEDE", "BIOPHYS", "BIOSTAT", "BL", "CATALAN", "CEE", "CHE", "CHEM", "CJS", "CLARCH", 
            "CLCIV", "CLIMATE", "CMPLXSYS", "COGSCI", "COMM", "COMP", "COMPLIT", "CSP", "CZECH", "DANCE", "DATASCI", "DIGITAL", 
            "DUTCH", "EARTH", "EAS", "ECON", "EDCURINS", "EDUC", "EEB", "EECS", "ELI", "ENGLISH", "ENGR", "ENS", "ENSCEN", "ENVIRON", 
            "ES", "ESENG", "FIN", "FRENCH", "FTVM", "GEOG", "GERMAN", "GREEK", "GREEKMOD", "GTBOOKS", "HEBREW", "HISTART", "HISTORY", "HONORS", 
            "HS", "HUMGEN", "INSTHUM", "INTLSTD", "INTMED", "IOE", "ISLAM", "ITALIAN", "JAZZ", "JUDAIC", "KINESLGY", "KRSTD", "LACS", 
            "LATIN", "LATINOAM", "LING", "LSWA", "MACROMOL", "MATH", "MATSCIE", "MCDB", "MECHENG", "MEDCHEM", "MELANG", "MEMS", "MENAS", 
            "MFG", "MICROBIOL", "MIDEAST", "MILSCI", "MKT", "MO", "MOVESCI", "MUSEUMS", "MUSICOL", "MUSMETH", "MUSTHTRE", "NATIVEAM", "NAVARCH",
            "NAVSCI", "NERS", "NURS", "ORGSTUDY", "PAT", "PATH", "PERSIAN", "PHARMACY", "PHARMSCI", "PHIL", "PHRMACOL", "PHYSICS", "PHYSIOL", 
            "PIBS", "POLISH", "POLSCI", "PORTUG", "PPE", "PSYCH", "PUBHLTH", "PUBPOL", "QMSS", "RCARTS", "RCASL", "RCCORE", "RCHUMS", "RCIDIV", 
            "RCLANG", "RCMUSIC", "RCNSCI", "RCSSCI", "REEES", "RELIGION", "ROMLANG", "ROMLING", "RUSSIAN", "SCAND", "SEAS", "SI", "SLAVIC", "SOC", 
            "SPACE", "SPANISH", "STATS", "STDABRD", "STRATEGY", "TCHNCLCM", "THEORY", "THTREMUS", "TO", "TURKISH", "UARTS", "UC", "UKR", "URP", 
            "WGS", "WRITING", "YIDDISH"]

export default {
    ClassNames, 
}
